language: php

php:
  - 5.5.9
  - 5.6
  - 7.2

services:
  - docker

before_script:
  - docker pull kennethreitz/httpbin
  - docker run -d --rm -p 80:80 kennethreitz/httpbin

script: phpunit --coverage-clover=coverage.xml